import {csv,report} from './export.js';
import {sample,validate,removeNodes,issues,mergeSource} from './model.js';
const suppliedFlow=await fetch(new URL('../flows/texas-questionnaire.json',import.meta.url)).then(r=>r.json()).then(validate);
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let flow;try{flow=validate(JSON.parse(localStorage.getItem('question-tree')));}catch{flow=structuredClone(suppliedFlow);}
let selected=new Set(),history=[],future=[],zoom=1,pan={x:60,y:50},references=[],search='',drag=null,runPath=[];
function checkpoint(){history.push(JSON.stringify(flow));if(history.length>80)history.shift();future=[];}
function save(){try{localStorage.setItem('question-tree',JSON.stringify(flow));$('#status').textContent='Saved on this browser';}catch{toast('Browser storage is full. Export your flow to keep a copy.');}}
function toast(msg){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),4000);}
function shell(){ $('#app').innerHTML=`<header><div class="brand"><span class="logo">⑂</span>Question Tree</div><span class="badge">INTERNAL WORKSPACE</span><input class="title" aria-label="Flow title" value="${esc(flow.title)}"><div class="actions"><button id="import">Import</button><button id="export">JSON</button><button id="csv" title="Export the entire project as CSV">Project CSV</button><button id="pdf" title="Print the entire project or save as PDF">Project PDF</button><button id="run" class="primary">▷ Test questionnaire</button></div></header><div class="layout"><aside><h2>Build your flow</h2><div class="palette"><button id="load-supplied">↳ Load your questionnaire</button><button id="add-question">◇ &nbsp; Question</button><button id="add-deal">▣ &nbsp; Deal outcome</button></div><div class="help">Drag cards to arrange your flow. Shift-click to select multiple cards. Drag the background to pan.</div><div class="section"><h2>Questions & outcomes</h2><input class="search" placeholder="Search your flow…" aria-label="Search nodes"><div class="node-list"></div></div><div class="section"><h2>Screenshot references</h2><button id="upload">＋ Upload screenshots</button><p class="help">Keep your original flow beside you while recreating questions and answer paths. Images stay in this session.</p><div id="references"></div></div></aside><main class="canvas"><div class="world"></div><div class="canvas-note">DASHED LINES = SCREENSHOT REFERENCES · ANSWERS STILL NEEDED</div><div class="controls"><button id="out" aria-label="Zoom out">−</button><span id="zoom">100%</span><button id="in" aria-label="Zoom in">＋</button><button id="fit">Fit flow</button></div></main><aside class="right"></aside></div><footer><span id="counts"></span><span id="status">Saved on this browser</span></footer>`;
$('.title').onchange=e=>{checkpoint();flow.title=e.target.value;save();};$('#load-supplied').onclick=()=>{modal('<h3>Load your screenshot flow?</h3><p class="muted">This adds missing questions by their original IDs and keeps your existing edits. Overlapping screenshots will not duplicate cards. Missing answers remain blank, and dashed connectors are references only.</p><button id="confirm-load" class="primary">Merge all supplied sections</button>');$('#confirm-load').onclick=()=>{checkpoint();flow=mergeSource(flow,suppliedFlow);selected.clear();$('.title').value=flow.title;$('.modal-backdrop').remove();render();fit();};};$('#add-question').onclick=()=>add('question');$('#add-deal').onclick=()=>add('deal');$('#export').onclick=exportFlow;$('#csv').onclick=()=>download(csv(flow),'question-tree.csv','text/csv;charset=utf-8');$('#pdf').onclick=()=>{const w=window.open('','_blank');if(!w){toast('Allow pop-ups to open the PDF report.');return;}w.document.open();w.document.write(report(flow));w.document.close();};$('#import').onclick=importFlow;$('#upload').onclick=upload;$('#run').onclick=()=>{runPath=[flow.start];runner();};$('.search').oninput=e=>{search=e.target.value;list();};$('#in').onclick=()=>setZoom(zoom*1.2);$('#out').onclick=()=>setZoom(zoom/1.2);$('#fit').onclick=fit;$('.canvas').addEventListener('pointerdown',pointerDown);$('.canvas').addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*(e.deltaY<0?1.1:.9),e.clientX,e.clientY);},{passive:false});render();}
function height(n){return (n.section?103:78)+n.answers.length*36;}
function render(){const world=$('.world');let edges='';for(const n of flow.nodes)for(let i=0;i<n.answers.length;i++){const a=n.answers[i],t=flow.nodes.find(x=>x.id===a.target);if(!t)continue;const x=n.x+235,y=n.y+(n.section?116:91)+i*36,tx=t.x,ty=t.y+40,d=Math.max(60,Math.abs(tx-x)/2);edges+=`<path d="M${x},${y} C${x+d},${y} ${tx-d},${ty} ${tx},${ty}" fill="none" stroke="#a8a1c6" stroke-width="1.7" marker-end="url(#arrow)"/>`;}
for(const link of flow.referenceLinks||[]){const n=flow.nodes.find(n=>n.id===link.source),t=flow.nodes.find(n=>n.id===link.target);if(!n||!t)continue;edges+=`<path d="M${n.x+117},${n.y+height(n)} L${t.x+117},${t.y}" fill="none" stroke="#b1b8c8" stroke-dasharray="5 5" marker-end="url(#arrow)"/>`;}
world.innerHTML=flow.groups.map(g=>{const ns=flow.nodes.filter(n=>g.members.includes(n.id));if(!ns.length)return '';const x=Math.min(...ns.map(n=>n.x))-22,y=Math.min(...ns.map(n=>n.y))-22,w=Math.max(...ns.map(n=>n.x+235))-x+22,h=Math.max(...ns.map(n=>n.y+height(n)))-y+22;return `<div class="group" data-group="${esc(g.id)}" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px"><span class="group-label">${esc(g.title)}</span></div>`;}).join('')+`<svg width="5000" height="5000"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#a8a1c6"/></marker></defs>${edges}</svg>`+flow.nodes.map(n=>`<div class="node ${n.type} ${selected.has(n.id)?'selected':''} ${n.id===flow.start?'start':''}" data-id="${esc(n.id)}" style="left:${n.x}px;top:${n.y}px"><div class="section-heading">${esc(n.section||'')}</div><div class="kind">${esc(n.questionCode|| (n.type==='deal'?'Deal outcome':'Question'))}</div><div class="text">${esc(n.title)}</div>${n.answers.map(a=>`<div class="answer"><span>${esc(a.label)}</span><span>${a.target?'↗':'○'}</span></div>`).join('')}</div>`).join('');transform();inspector();list();$('#counts').textContent=`${flow.nodes.filter(n=>n.type==='question').length} questions · ${flow.nodes.filter(n=>n.type==='deal').length} outcomes · ${flow.groups.length} groups · ${issues(flow).length} incomplete questions`;save();}
function transform(){$('.world').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('#zoom').textContent=Math.round(zoom*100)+'%';}
function setZoom(value,cx,cy){const r=$('.canvas').getBoundingClientRect(),x=cx===undefined?r.width/2:cx-r.left,y=cy===undefined?r.height/2:cy-r.top,n=Math.max(.15,Math.min(2,value));pan.x=x-(x-pan.x)*n/zoom;pan.y=y-(y-pan.y)*n/zoom;zoom=n;transform();}
function fit(){if(!flow.nodes.length)return;const r=$('.canvas').getBoundingClientRect(),minX=Math.min(...flow.nodes.map(n=>n.x)),minY=Math.min(...flow.nodes.map(n=>n.y)),w=Math.max(...flow.nodes.map(n=>n.x+235))-minX,h=Math.max(...flow.nodes.map(n=>n.y+height(n)))-minY;zoom=Math.max(.15,Math.min(1,(r.width-100)/w,(r.height-100)/h));pan={x:(r.width-w*zoom)/2-minX*zoom,y:(r.height-h*zoom)/2-minY*zoom};transform();}
function list(){$('.node-list').innerHTML=flow.nodes.filter(n=>n.title.toLowerCase().includes(search.toLowerCase())).map(n=>`<button data-find="${esc(n.id)}">${n.type==='deal'?'▣':'◇'} ${esc(n.title)}</button>`).join('');$('.node-list').onclick=e=>{const id=e.target.closest('[data-find]')?.dataset.find;if(!id)return;selected=new Set([id]);const n=flow.nodes.find(n=>n.id===id),r=$('.canvas').getBoundingClientRect();pan={x:r.width/2-(n.x+117)*zoom,y:r.height/2-(n.y+50)*zoom};render();};}
function inspector(){const n=flow.nodes.find(n=>selected.has(n.id)),el=$('.right');el.onclick=e=>{if(e.target.id==='undo')travel(history,future);if(e.target.id==='redo')travel(future,history);};el.innerHTML=`<h2>Properties</h2><div class="toolbar"><button id="undo" ${history.length?'':'disabled'}>↶ Undo</button><button id="redo" ${future.length?'':'disabled'}>↷ Redo</button></div>`;if(!n){el.innerHTML+='<h3>Make every answer count.</h3><p class="muted">Select a question to edit its answers and choose where each path leads.</p><p class="muted">Start with the example flow or import a saved Question Tree file.</p>';return;}
el.innerHTML+=`<h3>${selected.size>1?selected.size+' cards selected':n.type==='deal'?'Deal outcome':'Question details'}</h3><p class="muted">${esc(n.section||'')}${n.textIncomplete?' · Text clipped in source':''}</p><label>Text</label><textarea id="node-title" rows="3">${esc(n.title)}</textarea><div class="row"><button id="start">Set as start</button><button id="delete">Delete</button></div><div class="row"><button id="group" ${selected.size<2?'disabled':''}>Group</button><button id="ungroup">Ungroup</button></div>${n.type==='question'?`<label>Answers & destinations</label>${n.answers.map((a,i)=>`<div class="answer-edit"><input data-label="${i}" aria-label="Answer ${i+1}" value="${esc(a.label)}"><select data-target="${i}" aria-label="Destination ${i+1}"><option value="">Choose destination…</option>${flow.nodes.filter(t=>t.id!==n.id).map(t=>`<option value="${esc(t.id)}" ${a.target===t.id?'selected':''}>${esc(t.questionCode||t.id)} · ${esc(t.title)}</option>`).join('')}</select><button data-remove="${i}">Remove answer</button></div>`).join('')}<button id="answer">＋ Add answer</button>`:'<p class="muted">This is the end of a questionnaire path.</p>'}`;
detailsEditor(n,el);$('#node-title').onchange=e=>mutate(()=>n.title=e.target.value);$('#start').onclick=()=>mutate(()=>flow.start=n.id);$('#delete').onclick=()=>mutate(()=>{removeNodes(flow,selected);selected.clear();});$('#group').onclick=()=>mutate(()=>{flow.groups.forEach(g=>g.members=g.members.filter(id=>!selected.has(id)));flow.groups=flow.groups.filter(g=>g.members.length);flow.groups.push({id:crypto.randomUUID(),title:'Question group '+(flow.groups.length+1),members:[...selected]});});$('#ungroup').onclick=()=>mutate(()=>flow.groups=flow.groups.filter(g=>!g.members.some(id=>selected.has(id))));$('#answer')?.addEventListener('click',()=>mutate(()=>n.answers.push({label:'New answer',target:''})));el.querySelectorAll('[data-label]').forEach(e=>e.onchange=()=>mutate(()=>n.answers[+e.dataset.label].label=e.value));el.querySelectorAll('[data-target]').forEach(e=>e.onchange=()=>mutate(()=>n.answers[+e.dataset.target].target=e.value));el.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>mutate(()=>n.answers.splice(+e.dataset.remove,1)));}
function mutate(fn){checkpoint();fn();render();}function travel(from,to){if(!from.length)return;to.push(JSON.stringify(flow));flow=JSON.parse(from.pop());selected.clear();render();}
function add(type){mutate(()=>{const id=crypto.randomUUID();flow.nodes.push({id,type,title:type==='question'?'New question':'New deal type',x:(220-pan.x)/zoom,y:(160-pan.y)/zoom,answers:type==='question'?[{label:'Yes',target:''},{label:'No',target:''}]:[]});if(!flow.start)flow.start=id;selected=new Set([id]);});}
function pointerDown(e){if(e.button!==0||e.target.closest('.controls'))return;const card=e.target.closest('.node'),g=e.target.closest('.group');if(card){const id=card.dataset.id;if(e.shiftKey){selected.has(id)?selected.delete(id):selected.add(id);render();return;}if(!selected.has(id))selected=new Set([id]);checkpoint();drag={ids:[...selected],x:e.clientX,y:e.clientY,positions:flow.nodes.filter(n=>selected.has(n.id)).map(n=>({id:n.id,x:n.x,y:n.y}))};render();}else if(g){const group=flow.groups.find(x=>x.id===g.dataset.group);selected=new Set(group.members);checkpoint();drag={x:e.clientX,y:e.clientY,positions:flow.nodes.filter(n=>selected.has(n.id)).map(n=>({id:n.id,x:n.x,y:n.y}))};render();}else{selected.clear();drag={x:e.clientX,y:e.clientY,pan:{...pan}};inspector();}$('.canvas').setPointerCapture(e.pointerId);}
document.addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){pan={x:drag.pan.x+e.clientX-drag.x,y:drag.pan.y+e.clientY-drag.y};transform();}else{for(const p of drag.positions){const n=flow.nodes.find(n=>n.id===p.id);n.x=p.x+(e.clientX-drag.x)/zoom;n.y=p.y+(e.clientY-drag.y)/zoom;}render();}});document.addEventListener('pointerup',()=>{if(drag){drag=null;render();}});
function exportFlow(){const url=URL.createObjectURL(new Blob([JSON.stringify(flow,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='question-tree.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function pick(accept,multiple,fn){const input=document.createElement('input');input.type='file';input.accept=accept;input.multiple=multiple;input.onchange=()=>fn([...input.files]);input.click();}
function importFlow(){pick('.json',false,async files=>{try{const next=validate(JSON.parse(await files[0].text()));checkpoint();flow=next;selected.clear();$('.title').value=flow.title;render();fit();toast('Flow imported');}catch(e){toast(e.message);}});}
function upload(){pick('image/*',true,files=>{for(const f of files){if(!f.type.startsWith('image/')||f.size>20*1024*1024){toast('Choose images smaller than 20 MB.');continue;}references.push({name:f.name,url:URL.createObjectURL(f)});}$('#references').innerHTML=references.map((r,i)=>`<img class="reference" data-ref="${i}" src="${r.url}" alt="${esc(r.name)}"><div class="help">${esc(r.name)}</div>`).join('');$('#references').onclick=e=>{if(e.target.dataset.ref){const r=references[+e.target.dataset.ref];modal(`<h3>${esc(r.name)}</h3><img src="${r.url}" alt="${esc(r.name)}">`);}};});}
function modal(content){$('.modal-backdrop')?.remove();const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<div class="modal"><button id="close" style="float:right" aria-label="Close">✕</button>${content}</div>`;document.body.append(el);$('#close').onclick=()=>el.remove();el.onclick=e=>{if(e.target===el)el.remove();};}
function runner(){const n=flow.nodes.find(n=>n.id===runPath.at(-1));if(!n){toast('Add a start question first.');return;}modal(`<h2>Questionnaire preview</h2><p class="muted">${runPath.length>1?runPath.slice(0,-1).map(id=>esc(flow.nodes.find(n=>n.id===id)?.title||'')).join(' → '):'Follow the answers to discover the deal type.'}</p><h3>${esc(n.title)}</h3>${n.type==='deal'?'<p class="muted">Your recommended deal type</p>':`<div class="options">${n.answers.map((a,i)=>`<button data-run="${i}" ${a.target?'':'disabled'}>${esc(a.label)} ${a.target?'→':'· No destination'}</button>`).join('')}</div>${!n.answers.length?'<p>This question needs answers.</p>':''}`}<div class="row"><button id="back" ${runPath.length<2?'disabled':''}>Back</button><button id="restart">Restart</button></div>`);document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>{const target=n.answers[+b.dataset.run].target;if(runPath.includes(target)){toast('This answer creates a cycle. Fix its destination in the editor.');return;}runPath.push(target);runner();});$('#back').onclick=()=>{runPath.pop();runner();};$('#restart').onclick=()=>{runPath=[flow.start];runner();};}
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='Escape')$('.modal-backdrop')?.remove();if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();travel(e.shiftKey?future:history,e.shiftKey?history:future);}if((e.key==='Delete'||e.key==='Backspace')&&selected.size&&!$('.modal-backdrop')){e.preventDefault();mutate(()=>{removeNodes(flow,selected);selected.clear();});}});
shell();fit();

function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function detailsEditor(n,el){if(n.type!=='question')return;const panel=document.createElement('div');panel.className='section';const d=n.details||{};panel.innerHTML=`<h2>Question configuration</h2>${[['whyWeAsk','Why we ask'],['stage','Stage'],['responseType','Response type'],['persona','Persona'],['routeTag','Route tag']].map(([key,label])=>`<label>${label}</label><textarea data-detail="${key}" rows="2">${esc(d[key]||'')}</textarea>`).join('')}<label>Remember choice <select id="remember"><option value="">Not supplied</option><option value="true" ${d.rememberChoice===true?'selected':''}>Yes</option><option value="false" ${d.rememberChoice===false?'selected':''}>No</option></select></label>${[['visibility','Visibility rules (JSON)'],['canonicalMappings','Canonical mappings (JSON)']].map(([key,label])=>`<label>${label}</label><textarea data-json="${key}" rows="4">${d[key]?esc(JSON.stringify(d[key],null,2)):''}</textarea>`).join('')}<h2>Option values</h2>${n.answers.map((a,i)=>`<label>${esc(a.label)} — stored value</label><input data-value="${i}" value="${esc(a.value||'')}"><label>Unknown option <select data-unknown="${i}"><option value="">Not supplied</option><option value="true" ${a.unknown===true?'selected':''}>Yes</option><option value="false" ${a.unknown===false?'selected':''}>No</option></select></label>`).join('')}`;el.append(panel);panel.querySelectorAll('[data-detail]').forEach(e=>e.onchange=()=>mutate(()=>{n.details??={};n.details[e.dataset.detail]=e.value;}));panel.querySelectorAll('[data-json]').forEach(e=>e.onchange=()=>{try{const value=e.value.trim()?JSON.parse(e.value):null;mutate(()=>{n.details??={};n.details[e.dataset.json]=value;});}catch{toast('Invalid JSON. Correct it before saving.');}});panel.querySelector('#remember').onchange=e=>mutate(()=>{n.details??={};n.details.rememberChoice=e.target.value===''?null:e.target.value==='true';});panel.querySelectorAll('[data-value]').forEach(e=>e.onchange=()=>mutate(()=>n.answers[+e.dataset.value].value=e.value));panel.querySelectorAll('[data-unknown]').forEach(e=>e.onchange=()=>mutate(()=>n.answers[+e.dataset.unknown].unknown=e.value===''?null:e.value==='true'));}
