import {nodeWidth,nodeHeight,routeConnector,pointsPath} from './geometry.js';
import {pathFor} from './editing.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';
export function csv(flow){const columns=['ID','Section','Type','Prompt','Why we ask','Stage','Response type','Persona','Remember choice','Route tag','Answers and destinations (JSON)','Visibility (JSON)','Canonical mappings (JSON)','Text incomplete','Notes','Outgoing screenshot connectors (JSON)','Card formatting (JSON)'];return '\ufeff'+[columns,...flow.nodes.map(n=>{const d=n.details||{};return[n.id,n.section,n.type,n.title,d.whyWeAsk,d.stage,d.responseType,d.persona,d.rememberChoice,d.routeTag,JSON.stringify(n.answers),d.visibility?JSON.stringify(d.visibility):'',d.canonicalMappings?JSON.stringify(d.canonicalMappings):'',n.textIncomplete,n.notes,JSON.stringify((flow.referenceLinks||[]).filter(l=>l.source===n.id)),JSON.stringify({width:n.width,height:n.height,rotation:n.rotation,shape:n.shape,fill:n.fill,fontSize:n.fontSize,textColor:n.textColor,borderColor:n.borderColor,bold:n.bold,italic:n.italic})];})].map(row=>row.map(cell).join(',')).join('\r\n');}
export function report(flow){let pages='';const groups=[...flow.groups,{title:'Ungrouped',members:flow.nodes.filter(n=>!flow.groups.some(g=>g.members.includes(n.id))).map(n=>n.id)}];for(const g of groups){const ns=flow.nodes.filter(n=>g.members.includes(n.id));if(!ns.length)continue;const minX=Math.min(...ns.map(n=>n.x))-30,minY=Math.min(...ns.map(n=>n.y))-40,maxX=Math.max(...ns.map(n=>n.x+nodeWidth(n)+30))+30,maxY=Math.max(...ns.map(n=>n.y+nodeHeight(n)+30))+40,width=Math.max(600,maxX-minX),tileHeight=width*1.2;for(let top=minY;top<maxY;top+=tileHeight){let drawing='<defs><marker id="pdf-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto-start-reverse"><path d="M0,0 L8,4 L0,8" fill="#6754d9"/></marker></defs>';
for(const n of flow.nodes)for(const a of n.answers){const t=flow.nodes.find(t=>t.id===a.target);if(t)drawing+=drawLink(n,t,a,flow.nodes);}
for(const l of flow.referenceLinks||[]){const n=flow.nodes.find(n=>n.id===l.source),t=flow.nodes.find(n=>n.id===l.target);if(n&&t)drawing+=drawLink(n,t,l,flow.nodes);}
for(const n of ns){const w=nodeWidth(n),h=nodeHeight(n),fill=esc(n.fill|| (n.shape==='note'?'#fff1ac':'white')),stroke=esc(n.borderColor||'#6754d9');let shape=n.shape==='ellipse'?`<ellipse cx="${n.x+w/2}" cy="${n.y+h/2}" rx="${w/2}" ry="${h/2}" fill="${fill}" stroke="${stroke}"/>`:n.shape==='diamond'?`<polygon points="${n.x+w/2},${n.y} ${n.x+w},${n.y+h/2} ${n.x+w/2},${n.y+h} ${n.x},${n.y+h/2}" fill="${fill}" stroke="${stroke}"/>`:`<rect x="${n.x}" y="${n.y}" width="${w}" height="${h}" rx="${n.shape==='rectangle'?0:10}" fill="${fill}" stroke="${stroke}"/>`;const inset=n.shape==='diamond'?40:12;drawing+=`<g transform="rotate(${n.rotation||0} ${n.x+w/2} ${n.y+h/2})">${shape}<text x="${n.x+inset}" y="${n.y+24}" font-size="10">${esc(n.section||'')}</text><text x="${n.x+inset}" y="${n.y+40}" font-size="11">${esc(n.questionCode||n.id)}</text><foreignObject x="${n.x+inset}" y="${n.y+48}" width="${w-inset*2}" height="${Math.max(30,h-52)}"><div xmlns="http://www.w3.org/1999/xhtml" style="font:${n.italic?'italic ':''}${n.bold?'bold ':''}${n.fontSize||12}px Arial;color:${esc(n.textColor||'#243047')};overflow-wrap:anywhere">${esc(n.title)}</div></foreignObject></g>`;}
pages+=`<section class="diagram"><h2>${esc(g.title)} — diagram ${Math.floor((top-minY)/tileHeight)+1}</h2><p>Dashed lines are screenshot references. Unconfirmed answer routes are incomplete.</p><svg viewBox="${minX} ${top} ${width} ${tileHeight}" xmlns="http://www.w3.org/2000/svg">${drawing}</svg></section>`;}}
return `<!doctype html><html><head><title>${esc(flow.title)} — report</title><style>body{font:12px Arial;color:#233047;margin:30px}h1{font-size:24px}h2{font-size:16px}article{break-inside:avoid;border-top:1px solid #ddd;padding:16px 0}dt{font-weight:bold;margin-top:8px}dd{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}svg{width:100%;height:85vh}.diagram{break-after:page}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #ddd;padding:6px;overflow-wrap:anywhere}@media print{.print-tools{display:none}@page{size:A4;margin:15mm}body{margin:0}svg{height:235mm}} </style></head><body><div class="print-tools"><button onclick="window.print()">Print / Save as PDF</button><p>Choose Save as PDF in your browser’s print dialog.</p></div><h1>${esc(flow.title)}</h1><p>${flow.nodes.filter(n=>n.type==='question').length} questions · ${flow.groups.length} groups. Missing fields are unconfirmed. Screenshot images are session-only and are not embedded.</p>${pages}<h1>Question details</h1>${flow.nodes.map(n=>{const d=n.details||{};return `<article><h2>${esc(n.questionCode||n.id)} · ${esc(n.section)}</h2><p>${esc(n.title)}${n.textIncomplete?' [Source text clipped]':''}</p><dl>${[['Why we ask',d.whyWeAsk],['Stage',d.stage],['Response type',d.responseType],['Persona',d.persona],['Remember choice',d.rememberChoice],['Route tag',d.routeTag],['Visibility',d.visibility?JSON.stringify(d.visibility,null,2):null],['Canonical mappings',d.canonicalMappings?JSON.stringify(d.canonicalMappings,null,2):null],['Notes',n.notes]].map(([key,value])=>`<dt>${esc(key)}</dt><dd>${esc(value??'Not supplied')}</dd>`).join('')}</dl><table><thead><tr><th>Value</th><th>Answer</th><th>Unknown</th><th>Destination</th></tr></thead><tbody>${n.answers.map(a=>`<tr><td>${esc(a.value??'Not supplied')}</td><td>${esc(a.label)}</td><td>${esc(a.unknown??'Not supplied')}</td><td>${esc(a.target||'Not supplied')}</td></tr>`).join('')}</tbody></table>${n.answers.length?'':'<p>Answers not supplied.</p>'}<h3>Screenshot connector references</h3><ul>${(flow.referenceLinks||[]).filter(l=>l.source===n.id).map(l=>`<li>${esc(l.target)} — ${esc(l.label)} (${l.traced?'endpoints traced':'unconfirmed'})</li>`).join('')}</ul></article>`;}).join('')}</body></html>`;}

function drawLink(n,t,l,nodes){let d,x,y;if(l.routing==='auto'||l.points?.length){const r=routeConnector(n,t,nodes,l.points);d=pointsPath(r.points);const middle=r.points[Math.floor(r.points.length/2)];x=middle.x+6;y=middle.y-6;}else if(l.routing&&l.routing!=='original'){const r=pathFor(n,t,l.routing,l.lane||0);({d,x,y}=r);}else{const sy=n.y+nodeHeight(n),ty=t.y,lane=Math.min(n.x,t.x)-45-(l.lane||0)*24;d=l.kind==='bypass'?`M${n.x+nodeWidth(n)/2},${sy} L${lane},${sy+20} L${lane},${ty-20} L${t.x+nodeWidth(t)/2},${ty}`:`M${n.x+nodeWidth(n)/2},${sy} L${t.x+nodeWidth(t)/2},${ty}`;x=l.kind==='bypass'?lane+6:n.x+nodeWidth(n)/2+6;y=sy+18;}
return `<path d="${d}" stroke="${esc(l.color||(l.traced?'#168d88':'#6754d9'))}" stroke-width="${l.width||2}" fill="none" ${l.style==='dashed'||(!l.style&&l.traced===false)?'stroke-dasharray="5 5"':''} ${l.arrow==='none'?'':'marker-end="url(#pdf-arrow)"'} ${l.arrow==='both'?'marker-start="url(#pdf-arrow)"':''}/><text x="${x}" y="${y}" font-size="11">${esc(l.displayLabel??l.label??'')}</text>`;
}
