export const sample=()=>({version:1,title:'Deal qualification',start:'q1',nodes:[{id:'q1',type:'question',title:'Is this an existing customer?',x:100,y:160,answers:[{label:'Yes',target:'q2'},{label:'No',target:'q3'}]},{id:'q2',type:'question',title:'Are they adding a new product?',x:450,y:70,answers:[{label:'Yes',target:'d1'},{label:'No',target:'d2'}]},{id:'q3',type:'question',title:'Is there a defined budget?',x:450,y:330,answers:[{label:'Yes',target:'d3'},{label:'Not yet',target:'d4'}]},...['Expansion','Renewal','New business','Discovery'].map((title,i)=>({id:'d'+(i+1),title,type:'deal',x:800,y:30+i*170,answers:[]}))],groups:[]});
export function validate(flow){if(!flow||flow.version!==1||typeof flow.title!=='string'||!Array.isArray(flow.nodes)||!Array.isArray(flow.groups)||flow.nodes.length>2000)throw Error('Invalid Question Tree file.');const ids=new Set();for(const n of flow.nodes){if(typeof n.id!=='string'||ids.has(n.id)||!['question','deal','shape'].includes(n.type)||typeof n.title!=='string'||!Number.isFinite(n.x)||!Number.isFinite(n.y)||!Array.isArray(n.answers))throw Error('Invalid node.');for(const field of ['width','height','rotation','fontSize'])if(n[field]!==undefined&&(!Number.isFinite(n[field])||Math.abs(n[field])>10000))throw Error('Invalid card formatting.');if(n.width!==undefined&&n.width<100||n.height!==undefined&&n.height<30||n.fontSize!==undefined&&(n.fontSize<6||n.fontSize>72))throw Error('Invalid card size.');for(const field of ['fill','textColor','borderColor'])if(n[field]!==undefined&&!/^#[a-f0-9]{6}$/i.test(n[field]))throw Error('Invalid card color.');if(n.shape!==undefined&&!['rounded','rectangle','diamond','ellipse','note'].includes(n.shape))throw Error('Invalid card shape.');ids.add(n.id);for(const a of n.answers)if(typeof a.label!=='string'||typeof a.target!=='string')throw Error('Invalid answer.');}if(!ids.has(flow.start)&&flow.nodes.some(n=>n.type!=='shape'))throw Error('Start question is missing.');for(const n of flow.nodes)for(const a of n.answers)if(a.target&&!ids.has(a.target))throw Error('An answer points to a missing node.');for(const g of flow.groups)if(typeof g.id!=='string'||typeof g.title!=='string'||!Array.isArray(g.members)||g.members.some(id=>!ids.has(id)))throw Error('Invalid group.');for(const l of flow.referenceLinks||[]){if(!ids.has(l.source)||!ids.has(l.target))throw Error('Invalid connector endpoint.');if(l.points!==undefined&&(!Array.isArray(l.points)||l.points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y))))throw Error('Invalid connector bends.');}return flow;}
export function removeNodes(flow,ids){flow.deletedSourceIds=[...new Set([...(flow.deletedSourceIds||[]),...ids])];flow.nodes=flow.nodes.filter(n=>!ids.has(n.id));flow.referenceLinks=(flow.referenceLinks||[]).filter(l=>!ids.has(l.source)&&!ids.has(l.target));for(const n of flow.nodes)for(const a of n.answers)if(ids.has(a.target))a.target='';flow.groups=flow.groups.map(g=>({...g,members:g.members.filter(id=>!ids.has(id))})).filter(g=>g.members.length);if(ids.has(flow.start))flow.start=flow.nodes.find(n=>n.type!=='shape')?.id||'';}
export function issues(flow){return flow.nodes.filter(n=>n.type==='question'&&(!n.answers.length||n.answers.some(a=>!a.target||!a.label.trim())));}
export function mergeSource(current,source){
 const result=structuredClone(current);
 const ids=new Set(result.nodes.map(n=>n.id));
 const added=new Set();
 for(const n of source.nodes)if(!ids.has(n.id)&&!(current.deletedSourceIds||[]).includes(n.id)){result.nodes.push(structuredClone(n));ids.add(n.id);added.add(n.id);}
 // Existing nodes and group memberships are user-owned: preserve them exactly.
 for(const g of source.groups){const existing=result.groups.find(x=>x.id===g.id);const members=g.members.filter(id=>added.has(id));if(existing)existing.members.push(...members.filter(id=>!existing.members.includes(id)));else if(members.length)result.groups.push({...structuredClone(g),members});}
 const links=new Map((result.referenceLinks||[]).map(l=>[l.source+'|'+l.target,l]));
 for(const l of source.referenceLinks||[]){const key=l.source+'|'+l.target;if(!links.has(key)&&ids.has(l.source)&&ids.has(l.target)&&!(current.deletedReferenceLinks||[]).includes(key))links.set(key,structuredClone(l));}
 result.referenceLinks=[...links.values()];return validate(result);
}
